Light refactoring
SainsburyWellcomeCentre/crabs-exploration pull request #86
Opened 2023-11-17 16:16 UTC by sfmig

A first chunk of light refactoring:
- an example of avoiding [long parameter list](https://refactoring.guru/smells/long-parameter-list)
- reorganised the directories (moved bash scripts, guides and notebooks to the root level)

I figured we could merge to main this new structure and then I continue with closing currently open PRs. 

Next steps towards that:
- add stereo-calibration work (as it is in current state) 
    - PR #2
- add bash scripts:
     - to run video reencoding (PR #31) 
     - to run reencoding+frame extraction (PR #78)
- add/update guides
    - PRs #81, 
    - PR #75
- add exclude pattern feature to combine annotations, with tests 
    - PR #77
- finish test for frame extraction 
    - PR #24

2023-11-17 18:30 UTC, samcunliffe approved these changes
👍

2023-11-17 18:34 UTC, samcunliffe requested changes

2023-11-17 18:34 UTC, samcunliffe commented on crabs/dense_optical _flow/estimate_optical_flow_on_video.py
Wait. We've removed this but didn't re-add. Presumably `crabs/dense_optical_flow/*.py`.

2023-11-20 07:51 UTC, sfmig commented on crabs/dense_optical _flow/estimate_optical_flow_on_video.py
Yeah that is actually intended! We are not using this optic flow estimation anymore (we are doing a simpler computation for it instead). I think it's good enough to have it in the history if we ever need to retrieve it, but we can keep the codebase cleaner by removing it from the src for now.

Let me know if all ok

2023-11-20 08:18 UTC, samcunliffe approved these changes

2023-11-20 08:28 UTC, merged